vim.opt.number = true
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.numberwidth = 2
vim.opt.relativenumber = true
vim.opt.signcolumn = 'yes'
vim.opt.cursorline = false
vim.opt.termguicolors = true
vim.opt.showmode = false
vim.opt.background= "dark"
vim.opt.showtabline = 2-- }}}
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.undofile = true
vim.opt.breakindent = true
vim.opt.smarttab = true
vim.opt.cindent = true
vim.opt.autoindent = true
vim.opt.wrap = false
vim.opt.hidden = true
vim.opt.textwidth = 300
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.autoindent = true
vim.opt.expandtab = true
vim.opt.list = true
vim.opt.listchars = 'trail:·,nbsp:◇,tab:→ ,extends:▸,precedes:◂'
vim.opt.clipboard = 'unnamedplus'
vim.opt.timeoutlen = 500
vim.opt.updatetime = 200
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.history = 50
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.mouse = "a"
vim.opt.wrap = false
vim.opt.foldmethod = "marker"

vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.vimwiki_folding = 'custom'
